head:
  logo: "logo.svg"
  name: "Association Name"
  icon: "logo.ico"
  description: "Description"
  slogan:
    font: "Sofia, sans-serif"
    top: "Your"
    bottom: "Slogan"
body:
  departments:
    - name: "Football"
      contacts:
        - name: "Don Joe"
          title: "responsible"
          description: "responsible for Example Sport"
          tel: "555123456"
      gallery: 
        - title: "Example Image"
          src: "example-image.webp"
footer:
  background_image: "example-background.svg"
  socials:
    - account: "fc_example_1900"
      link: "https://www.instagram.com/fc_example_1900/"
      image: "insta.svg"
  contacts:
    - title: "Board"
      name: "John Doe"
      address: "Example str. 42 | 12345 City"
      email: "john.doe@example.com"
      tel: "555 / 123456"
      responsible: true
fonts:
  - name: "Sofia"
    src: "Sofia-Regular.woff"
    font_weight: "normal"
    font_style: "normal"
lang_file: "en.yaml"
linked_sites:
  - name: "Cloud"
    url: "https://cloud.example.com/"
    type: "link"
  - name: "Files"
    type: "dropdown"
    links:
      - name: "Membership"
        url: "https://cloud.example.com/membership"
      - name: "Rental"
        url: "https://cloud.example.com/rental"
  - name: "Calendars"
    type: "dropdown"
    links:
      - name: "Sports home occupancy"
        url: "https://cloud.example.com/calendars/occupancy"
  
custom_pages:
  - name: "Dataprotection"
    file: "dataprotection.html"