name: Deploy to GitHub Pages

on:
  push:
    branches:
      - fix-gitlab-pages 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install
      working-directory: ./docs

    - name: Build Jekyll site
      run: bundle exec jekyll build
      working-directory: ./docs

    - name: List _site directory
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_site


    - name: List gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        ls -la
