name: Docker Image CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag julian47/association-as-code:$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    - name: Run Docker image
      run: docker run julian47/association-as-code:$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    - name: Test
      run: |
        docker run --rm julian47/association-as-code:$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
