name: Docker Image CI

on: [push, pull_request]

env:
  TEST_TAG: julian47/association-as-code:test
  LATEST_TAG: julian47/association-as-code:latest
  CONTAINER_NAME: aas_test

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      - name: Test
        run: |
          docker run --rm -d --name ${{ env.CONTAINER_NAME }} ${{ env.TEST_TAG }}
      - name: Curl
        uses: indiesdev/curl@v1.1
        with:
          url: http://127.0.0.1:80
      - name: Remove docker container
        run: |
          docker rm -f ${{ env.CONTAINER_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
